#! /bin/bash
set -x
. conf

# Build a custom UEFI linux based PBA image
VERSIONINFO="$(git describe --dirty)" || VERSIONINFO='tarball'
BUILDTYPE='UEFI64'
BUILDIMG="$BUILDTYPE-$VERSIONINFO.img"

# Check if running as root
if [ $(id -u) -ne 0 ]; then
    echo 'Must be run as root!'
    exit 1
fi

# Check prereqs
[ -f scratch/$SYSLINUX/efi64/efi/syslinux.efi ] || { echo 'Prereqs not available'; exit 1; }
[ -f scratch/$SYSLINUX/efi64/com32/elflink/ldlinux/ldlinux.e64 ] || { echo 'Prereqs not available'; exit 1; }
[ -f scratch/buildroot/64bit/images/bzImage ] || { echo 'Prereqs not available'; exit 1; }
[ -f scratch/buildroot/64bit/images/rootfs.cpio.xz ] || { echo 'Prereqs not available'; exit 1; }
[ -f scratch/buildroot/64bit/target/sbin/linuxpba ] || { echo 'Prereqs not available'; exit 1; }
[ -f scratch/buildroot/64bit/target/sbin/sedutil-cli ] || { echo 'Prereqs not available'; exit 1; }
[ -f buildroot/syslinux.cfg ] || { echo 'Prereqs not available'; exit 1; }
echo "Building $BUILDTYPE image"
  
# Clean slate
rm -rf $BUILDTYPE
mkdir $BUILDTYPE
cd $BUILDTYPE

# Create image file and loopback device
dd if=/dev/zero of=$BUILDIMG bs=1M count=32
sfdisk $BUILDIMG < ../layout.sfdisk
LOOPDEV=$(losetup --show -f -o 1048576 $BUILDIMG)
mkfs.vfat $LOOPDEV -n $BUILDTYPE

# Mount the image
mkdir image
mount $LOOPDEV image
chmod 644 image

# Copy the system onto the image
mkdir -p image/EFI/boot
cp ../scratch/$SYSLINUX/efi64/efi/syslinux.efi image/EFI/boot/bootx64.efi
cp ../scratch/$SYSLINUX/efi64/com32/elflink/ldlinux/ldlinux.e64 image/EFI/boot/
cp ../scratch/buildroot/64bit/images/bzImage image/EFI/boot/
cp ../scratch/buildroot/64bit/images/rootfs.cpio.xz image/EFI/boot/
cp ../buildroot/syslinux.cfg image/EFI/boot/

# Clean up
umount image
losetup -d $LOOPDEV
gzip $BUILDIMG
