#! /bin/bash
set -x
. conf

function die {
    echo 'An error has occured! Please fix this and start over!'
    exit 1
}

cd scratch

# Clean slate
rm buildroot-*
rm -rf buildroot
curl $BUILDROOT/buildroot-$BUILDROOT_TAG.tar.gz -O || die
tar xf buildroot-$BUILDROOT_TAG.tar.gz
mv buildroot-$BUILDROOT_TAG buildroot

cd buildroot

# Add out of tree build directories and files
mkdir 64bit
cp ../../buildroot/64bit/.config 64bit/
cp ../../buildroot/64bit/* 64bit/
cp -r ../../buildroot/64bit/overlay 64bit/

# Add the buildroot packages
sed -i '/sedutil/d' package/Config.in
sed -i '/menu "System tools"/a \\tsource "package/sedutil/Config.in"' package/Config.in
rm -rf package/sedutil
cp -r ../../buildroot/packages/sedutil/ package/

# Make a distribution from the current source
cd ../../..
autoreconf -i
./configure
make dist
mkdir images/scratch/buildroot/dl/
cp sedutil-*.tar.gz images/scratch/buildroot/dl/
make distclean

# Expand the distribution tarball so we can use it as the Buildroot override.
# Override location is specified in the 'local.mk' file in buildroot/64bit
# directory.
# See also section 8.12.6 "Using Buildroot during development" in the
# Buildroot user manual.
cd images/scratch/buildroot/dl
tar xf sedutil-*.tar.gz
cd ..

# Build the rootfs for 64 bit systems
echo 'Making the 64bit PBA Linux system'
make O=64bit 2>&1 | tee 64bit/build_output.txt

cd ../..
