#! /bin/bash
# Setup versions for image components
# This script should be sourced by the other scripts
BUILDROOT_URL='https://git.buildroot.net/buildroot/snapshot/'
BUILDROOT_VER='buildroot-2020.11.1'

export BR2_CCACHE_DIR="$PWD/.br_ccache/"
export BR2_EXTERNAL="$PWD/sedutil/"
