#! /bin/bash
#  Setup versions for image components
#  This script should be sourced by the other scripts
SYSLINUX='syslinux-6.03'
BUILDROOT='https://git.buildroot.net/buildroot/snapshot/'
BUILDROOT_TAG='2020.11.1'
